# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: BARC VK4BA
subtitle: Brisbane Amateur Radio Club
description: >-
  The Brisbane Amateur Radio Club (BARC) promotes the hobby of
  Amateur (Ham) Radio and Electronics.

  Our members come from all walks of life but share a common interest in radio
  communications and associated electronics and technology.

url: ""         # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""     # the subpath of your site, e.g. /blog

repository: barcvk4ba/barcvk4ba.github.io

#facebook_username: Brisbane-Amateur-Radio-Club-BARC-VK4BA-879007988845541
#email: vk4ba@qls.net

# Timezone
timezone: Australia/Brisbane

#
# Define the list of links in the footer
#
footer:
    links:
      - label: Facebook
        url: https://www.facebook.com/Brisbane-Amateur-Radio-Club-BARC-VK4BA-879007988845541
        icon: fab fa-facebook
      - label: GitHub
        url: https://github.com/barcvk4ba
        icon: fab fa-github
      - label: vk4ba@qls.net
        url: mailto:vk4ba@qls.net
        icon: fas fa-envelope

#
# Build settings
# Note: we have to use minimal-mistakes as a remote theme for GitHub Pages
#
remote_theme: "mmistakes/minimal-mistakes@4.19.2"
minimal_mistakes_skin: "default" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

#
# Configure home page post pagination
#
paginate: 5
paginate_path: /news/page:num/

# Define our collections
collections:
    projects:
        output: true
        permalink: /:collection/:name
    articles:
        output: true
        permalink: /:collection/:name


#
# Define the standard page layout that we can apply
# using the `defaults` key below to posts, pages and
# our various collections
#
default_layout: &layout
    layout: single
    header:
        overlay_image: /assets/images/vk4ba.png
        overlay_filter: "0.5"
        show_overlay_excerpt: false
    sidebar:
        nav: leftnav           # sidebar navigation list in _data/navigation.yml
    author_profile: false
    read_time: true
    comments: false
    share: false
    related: false

#
# Estabilish defaults for Pages and Posts and other Collections
#
defaults:
    # _posts
    - scope:
        path: ""
        type: posts
      values: *layout

    # _pages
    - scope:
        path: ""
        type: pages
      values: *layout

    # _projects collection
    - scope:
        path: ""
        type: projects
      values: *layout

    # _articles collection
    - scope:
        path: ""
        type: articles
      values: *layout


#
# Include the specific folders we want
#
include:
    - _pages
    - _posts
    - _projects
    - _articles


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - .vendor/
    - vendor/
    - README.md
    - serve.sh

# List of plugins to run for the site
plugins:
    - jekyll-feed
    - jekyll-paginate
    - jekyll-include-cache

