# This is a basic workflow to help you get started with Actions

name: Nightly Rebuild (gh-pages)

# Schedule the action to occur at 00:05 AEST (+10:00). We have to adjust
# the cron value for UTC as this is what GitHub runs.
#
on:
  push:
    branches:
      - master
  schedule:
    - cron: "5 14 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Standard usage
    - uses:  helaili/jekyll-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: 'gh-pages'

