# This is a basic workflow to help you get started with Actions

name: Nightly Rebuild

# Schedule the action to occur at 00:05 AEST (+10:00). We have to adjust
# the cron value for UTC as this is what GitHub runs.
#
on:
  schedule:
    - cron: "5 14 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer $REBUILD_TOKEN"
        env:
          # You must create a personal token with repo access as GitHub does
          # not yet support server-to-server page builds.
          REBUILD_TOKEN: ${{ secrets.REBUILD_TOKEN }}
